#!/usr/bin/env python3
"""Generate the exhaustive, one-entry-per-procedure Thor2D reference."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "thor2d"
OUT = ROOT / "docs" / "wiki" / "Complete_API.md"
PROC_RE = re.compile(r"^([A-Z][A-Za-z0-9_]*)\s*::\s*proc(?:.*)$", re.MULTILINE)

def main() -> int:
    lines = [
        "# Complete API Reference (v0.11)", "",
        "This page contains one entry for every public procedure exported by",
        "`thor2d`. It is generated by `python3 scripts/generate_api_docs.py`.",
        "The module pages add semantics, error rules, LOVE differences and examples.", "",
    ]
    total = 0
    for path in sorted(SRC.glob("*.odin")):
        entries = PROC_RE.findall(path.read_text())
        if not entries:
            continue
        lines += [f"## `{path.stem}`", "", f"Source: `src/thor2d/{path.name}`", ""]
        source = path.read_text()
        text = source.splitlines()
        for name in entries:
            start = next(i for i, x in enumerate(text) if re.match(rf"^{re.escape(name)}\s*::\s*proc", x))
            declaration = []
            for part in text[start:]:
                declaration.append(part)
                if "{" in part:
                    break
            signature = "\n".join(declaration).split("{", 1)[0].strip()
            comments = []
            previous = start - 1
            while previous >= 0 and text[previous].strip().startswith("//"):
                comments.insert(0, text[previous].strip()[2:].strip())
                previous -= 1
            url = f"https://github.com/Bruno-BRG/Thor2D/blob/master/src/thor2d/{path.name}#L{start + 1}"
            lines += [f"### `{name}`", "", f"```odin\n{signature}\n```", ""]
            if comments:
                lines += ["\n".join(comments), ""]
            lines += [f"[Implementation and error branches]({url})", ""]
            total += 1
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} with {total} procedure entries")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
