#!/usr/bin/env python3
"""Generate the exhaustive, one-entry-per-procedure Thor2D reference."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "thor2d"
OUT = ROOT / "docs" / "wiki" / "Complete_API.md"
PROC_RE = re.compile(r"^([A-Z][A-Za-z0-9_]*)\s*::\s*proc(?:.*)$", re.MULTILINE)

def main() -> int:
    lines = [
        "# Complete API Reference (v0.11)", "",
        "This page contains one entry for every public procedure exported by",
        "`thor2d`. It is generated by `python3 scripts/generate_api_docs.py`.",
        "The module pages add semantics, error rules, LOVE differences and examples.", "",
    ]
    total = 0
    for path in sorted(SRC.glob("*.odin")):
        entries = PROC_RE.findall(path.read_text())
        if not entries:
            continue
        lines += [f"## `{path.stem}`", "", f"Source: `src/thor2d/{path.name}`", ""]
        text = path.read_text().splitlines()
        for name in entries:
            line = next((x.strip() for x in text if re.match(rf"^{re.escape(name)}\s*::\s*proc", x)), f"{name} :: proc")
            lines += [f"### `{name}`", "", f"```odin\n{line}\n```", "", f"See [API index](Api_Reference.md) and the relevant module page for behavior.", ""]
            total += 1
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} with {total} procedure entries")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
